service: norshukri-c5-serverless-3
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  deploymentBucket:
    name: cohort5.deployment


functions:
  norapi:
    handler: index.shukritwo
    events:
      - httpApi:
          path: /
          method: get
          
  shukripost:
    handler: index.shukriposttwo
    events:
      - httpApi:
          path: /shukripost
          method: post
      - sqs:
          arn:
            Fn::GetAtt:
              - ShukriQueue
              - Arn


resources:
  Resources:
    ShukriQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "shukri-queue"
    ShukriS3Bucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: "shukri-s3-bucket"

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001